spring:
  profiles: develop-psql
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/dicedb?currentSchema=game
#    username: postgres
#    password: postgres
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
##    show-sql: true
#    properties:
#      hibernate:
#        ddl-auto: update
##        generate_statistics: true
#        format_sql: true
#        jdbc: 
#          lob:
#            non_contextual_creation: true
#  
#  devtools:
#    restart:
#        enabled: true
#
#  logging:
#    level:
#    org:
#      hibernate:
#        type: trace
#        stat: debug
#
server:
#  address: 127.0.0.1
  port: 8000
---

spring:
    profiles:
        active: develop-psql